server:
  port: 8081
#DB Configuration
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.207.23.242:3306/Test
    username: Test
    password: xjh888
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging
logging:
  level:
    com.xc.springboot: debug
